USE [master]
GO
/****** Object:  Database [Parqueadero]    Script Date: 10/25/2021 10:22:13 PM ******/
CREATE DATABASE [Parqueadero]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Parqueadero', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Parqueadero.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Parqueadero_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Parqueadero_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Parqueadero] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Parqueadero].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Parqueadero] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Parqueadero] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Parqueadero] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Parqueadero] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Parqueadero] SET ARITHABORT OFF 
GO
ALTER DATABASE [Parqueadero] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Parqueadero] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Parqueadero] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Parqueadero] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Parqueadero] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Parqueadero] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Parqueadero] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Parqueadero] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Parqueadero] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Parqueadero] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Parqueadero] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Parqueadero] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Parqueadero] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Parqueadero] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Parqueadero] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Parqueadero] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Parqueadero] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Parqueadero] SET RECOVERY FULL 
GO
ALTER DATABASE [Parqueadero] SET  MULTI_USER 
GO
ALTER DATABASE [Parqueadero] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Parqueadero] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Parqueadero] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Parqueadero] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Parqueadero] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Parqueadero] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Parqueadero', N'ON'
GO
ALTER DATABASE [Parqueadero] SET QUERY_STORE = OFF
GO
USE [Parqueadero]
GO
/****** Object:  Table [dbo].[Bahia]    Script Date: 10/25/2021 10:22:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Bahia](
	[IdBahia] [int] NOT NULL,
	[IdParqueadero] [int] NULL,
	[Disponible] [varchar](50) NULL,
 CONSTRAINT [PK_Bahia] PRIMARY KEY CLUSTERED 
(
	[IdBahia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Pago]    Script Date: 10/25/2021 10:22:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pago](
	[IdPago] [int] NOT NULL,
	[IdBahia] [int] NOT NULL,
	[IdVehiculo] [int] NOT NULL,
	[Tiempo] [varchar](50) NULL,
	[Costo] [varchar](50) NULL,
	[Fecha] [date] NOT NULL,
 CONSTRAINT [PK_Pago] PRIMARY KEY CLUSTERED 
(
	[IdPago] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Parqueadero]    Script Date: 10/25/2021 10:22:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Parqueadero](
	[IdParqueadero] [int] NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Ubicacion] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Parqueadero] PRIMARY KEY CLUSTERED 
(
	[IdParqueadero] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Persona]    Script Date: 10/25/2021 10:22:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Persona](
	[IdPersona] [int] NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Persona] PRIMARY KEY CLUSTERED 
(
	[IdPersona] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tarifa]    Script Date: 10/25/2021 10:22:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tarifa](
	[IdTarifa] [int] NOT NULL,
	[Costo] [varchar](50) NULL,
	[IdTipo] [int] NOT NULL,
 CONSTRAINT [PK_Tarifa] PRIMARY KEY CLUSTERED 
(
	[IdTarifa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TipoVehiculo]    Script Date: 10/25/2021 10:22:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TipoVehiculo](
	[IdTipo] [int] NOT NULL,
	[Clase] [varchar](50) NOT NULL,
 CONSTRAINT [PK_TipoVehiculo] PRIMARY KEY CLUSTERED 
(
	[IdTipo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Vehiculo]    Script Date: 10/25/2021 10:22:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Vehiculo](
	[IdVehiculo] [int] NOT NULL,
	[Marca] [nchar](10) NULL,
	[IdPersona] [int] NOT NULL,
	[IdTipo] [int] NOT NULL,
 CONSTRAINT [PK_Vehiculo] PRIMARY KEY CLUSTERED 
(
	[IdVehiculo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Bahia]  WITH CHECK ADD  CONSTRAINT [FK_Bahia_Parqueadero] FOREIGN KEY([IdParqueadero])
REFERENCES [dbo].[Parqueadero] ([IdParqueadero])
GO
ALTER TABLE [dbo].[Bahia] CHECK CONSTRAINT [FK_Bahia_Parqueadero]
GO
ALTER TABLE [dbo].[Pago]  WITH CHECK ADD  CONSTRAINT [FK_Pago_Bahia] FOREIGN KEY([IdBahia])
REFERENCES [dbo].[Bahia] ([IdBahia])
GO
ALTER TABLE [dbo].[Pago] CHECK CONSTRAINT [FK_Pago_Bahia]
GO
ALTER TABLE [dbo].[Pago]  WITH CHECK ADD  CONSTRAINT [FK_Pago_Vehiculo] FOREIGN KEY([IdVehiculo])
REFERENCES [dbo].[Vehiculo] ([IdVehiculo])
GO
ALTER TABLE [dbo].[Pago] CHECK CONSTRAINT [FK_Pago_Vehiculo]
GO
ALTER TABLE [dbo].[Tarifa]  WITH CHECK ADD  CONSTRAINT [FK_Tarifa_TipoVehiculo] FOREIGN KEY([IdTipo])
REFERENCES [dbo].[TipoVehiculo] ([IdTipo])
GO
ALTER TABLE [dbo].[Tarifa] CHECK CONSTRAINT [FK_Tarifa_TipoVehiculo]
GO
ALTER TABLE [dbo].[Vehiculo]  WITH CHECK ADD  CONSTRAINT [FK_Vehiculo_Persona] FOREIGN KEY([IdPersona])
REFERENCES [dbo].[Persona] ([IdPersona])
GO
ALTER TABLE [dbo].[Vehiculo] CHECK CONSTRAINT [FK_Vehiculo_Persona]
GO
ALTER TABLE [dbo].[Vehiculo]  WITH CHECK ADD  CONSTRAINT [FK_Vehiculo_TipoVehiculo] FOREIGN KEY([IdTipo])
REFERENCES [dbo].[TipoVehiculo] ([IdTipo])
GO
ALTER TABLE [dbo].[Vehiculo] CHECK CONSTRAINT [FK_Vehiculo_TipoVehiculo]
GO
USE [master]
GO
ALTER DATABASE [Parqueadero] SET  READ_WRITE 
GO
